{
    "lang": "cat",
    "year": 2021,
    "month": 12,
    "day": 31,
    "title": "31 de desembre de 2019",
    "body": " L'Oficina de l'OMS a la Xina va rebre un av\u00eds de diversos casos de pneum\u00f2nia de causa desconeguda a la ciutat de Wuhan. Posteriorment, es va determinar que el causant de la malaltia era el coronavirus SARS-CoV-2",
    "eventYear": "2019",
    "image": "https://calendario-cientifico-escolar.github.io/images/personajes/365.png"
}